/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * The name of the connector.
 */
export enum ConnectorEnum {
  Stripe = "STRIPE",
  DummyPay = "DUMMY-PAY",
  Wise = "WISE",
  Modulr = "MODULR",
  CurrencyCloud = "CURRENCY-CLOUD",
  BankingCircle = "BANKING-CIRCLE",
}
