/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ErrorsEnumEnum {
  Internal = "INTERNAL",
  InsufficientFund = "INSUFFICIENT_FUND",
  Validation = "VALIDATION",
  Conflict = "CONFLICT",
  NoScript = "NO_SCRIPT",
  CompilationFailed = "COMPILATION_FAILED",
  MetadataOverride = "METADATA_OVERRIDE",
}
