/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum ErrorCode {
    Validation = "VALIDATION",
    NotFound = "NOT_FOUND",
}

export class ErrorT extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "errorCode" })
    errorCode: ErrorCode;

    @SpeakeasyMetadata()
    @Expose({ name: "errorMessage" })
    errorMessage: string;
}
