/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WorkflowOccurrence } from "./workflowoccurrence";
import { Expose, Type } from "class-transformer";

/**
 * The workflow occurrence
 */
export class GetWorkflowOccurrenceResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => WorkflowOccurrence)
    data: WorkflowOccurrence;
}
