/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum PaymentStatusEnum {
  Pending = "PENDING",
  Active = "ACTIVE",
  Terminated = "TERMINATED",
  Failed = "FAILED",
}
