/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class AddMetadataOnTransactionRequest extends SpeakeasyBase {
    /**
     * Use an idempotency key
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=Idempotency-Key" })
    idempotencyKey?: string;

    /**
     * metadata
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: Record<string, string>;

    /**
     * Set async mode.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=async" })
    async?: boolean;

    /**
     * Set the dryRun mode. Dry run mode doesn't add the logs to the database or publish a message to the message broker.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=dryRun" })
    dryRun?: boolean;

    /**
     * Name of the ledger.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=ledger" })
    ledger: string;

    /**
     * Transaction ID.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=txid" })
    txid: number;
}

export class AddMetadataOnTransactionResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errorResponse?: shared.ErrorResponse;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
