/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Type } from "class-transformer";

export class GetFlowRequest extends SpeakeasyBase {
  /**
   * The flow id
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=flowId",
  })
  flowId: string;
}

export class GetFlowResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * General error
   */
  @SpeakeasyMetadata()
  error?: shared.ErrorT;

  /**
   * The workflow
   */
  @SpeakeasyMetadata()
  getWorkflowResponse?: shared.GetWorkflowResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
