/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetWorkflowOccurrenceRequest extends SpeakeasyBase {
  /**
   * The flow id
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=flowId",
  })
  flowId: string;

  /**
   * The occurrence id
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=runId",
  })
  runId: string;
}

export class GetWorkflowOccurrenceResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * General error
   */
  @SpeakeasyMetadata()
  error?: shared.ErrorT;

  /**
   * The workflow occurrence
   */
  @SpeakeasyMetadata()
  getWorkflowOccurrenceResponse?: shared.GetWorkflowOccurrenceResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
